language: python

python:
  - "3.7"
  - "3.8"

sudo: enabled

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
